spring.application.name=asset-manager

# MariaDB Database
spring.datasource.url=jdbc:mariadb://localhost:3306/assetdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# MySQL Database
#spring.datasource.url=jdbc:mariadb://particle.mysql.database.azure.com:3306/pam-test?createDatabaseIfNotExist=true
#spring.datasource.username=pam_test
#spring.datasource.password=Password123!

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Swagger order
# Ordina i metodi dello Swagger
springdoc.swagger-ui.operationsSorter=method

# JWT - Access Token (breve durata)
#jwt.secret=ZHVtbXktc2VjcmV0LWtleS1jaGF0Z3B0LTEyMy00NTY=
# Durata 15 minuti
#jwt.expiration=900000
# Durata 60 minuti
#jwt.expiration=3600000

# Microsoft Azure AD
#azure.activedirectory.client-id=6618f68e-5225-4b93-ae0c-42eb4425432e
# Al momento "common" poi sarà inserito il tenant.
#azure.activedirectory.tenant-id=cf945c81-7814-4635-97ff-08679498fdc3

azure.activedirectory.client-id=IL_TUO_CLIENT_ID_DA_AZURE_DA_CONFINGURARE
# Al momento "common" poi sarà inserito il tenant.
azure.activedirectory.tenant-id=common
azure.activedirectory.jwks-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys

# JWT Refresh Token (lunga durata)
#jwt.refresh.secret=cmVmcmVzaC1zZWNyZXQta2V5LWNoYXRncHQtNzg5LTEwMQ==
# Durata 2 minuti
#jwt.refresh.expiration=120000
# Durata 60 minuti
#jwt.refresh.expiration=3600000
# Durata 7 giorni
#jwt.refresh.expiration=604800000

# Durata cache
cache.ttl=28800000
#cache.duration.hours=8

# Cancella l'errore di RTSP
logging.level.org.apache.coyote.http11=ERROR

# Path ricevute (receipts)
receipts.dir=receipts/

# Swagger Background
springdoc.swagger-ui.customCssUrl=/swagger-dark.css