package com.particle.asset.manager.enums;

public enum MovementOperations
{
    OK, BAD_REQUEST,
    INVALID_MOVEMENT_TYPE, ASSET_STATE_BLOCKS_OPERATION,
    ASSET_NOT_FOUND, MOVEMENT_NOT_FOUND,
    ASSET_MOVEMENT_NOT_FOUND, USER_NOT_FOUND,
    USER_MOVEMENT_NOT_FOUND, INVALID_FILE_NAME,
    BUSINESS_UNIT_MISMATCH, FILE_IS_MISSING,
    INVALID_TARGET_ROLE, INVALID_RETURN_USER,
    DIFFERENT_ASSET_CODE // codice asset e movement non combaciano
}
