package com.particle.asset.manager.enums;

public enum TicketOperations
{
    OK, BAD_REQUEST,
    OPERATION_ERROR, USER_NOT_FOUND,
    ASSET_NOT_FOUND, ASSET_TYPE_NOT_FOUND,
    TICKET_NOT_FOUND, INVALID_USER_TYPE,
    CANNOT_INTERACT_WITH, ALREADY_REPLIED,
    CANNOT_CLOSE, DIFFERENT_USER,
    INVALID_STATUS, LONG_MESSAGE,
    CANNOT_CONFIRM_CLOSURE
}
